[package]
name = "mpdrome-subsonic"
version = "0.1.0"
edition = "2024"

[dependencies]
submarine.workspace = true
tokio.workspace = true
color-eyre.workspace = true

mpdrome-bridge.workspace = true
mpdrome-mpd-model.workspace = true
